"""File text extractors used by indexing pipelines."""

from .contract import ExtractedDocument, TextBlock, blocks_from_legacy_text, document_from_legacy_text
from .files import (
    extract_csv,
    extract_doc,
    extract_doc_meta,
    extract_docx,
    extract_html,
    extract_image,
    extract_pdf,
    extract_pdf_document,
    extract_pptx,
    extract_pptx_document,
    extract_rtf,
    extract_spreadsheet,
    extract_spreadsheet_document,
    extract_text,
    extract_xls,
    extract_xls_document,
    extract_xlsx,
    extract_xlsx_document,
    ocr_pdf,
)

__all__ = [
    "ExtractedDocument",
    "TextBlock",
    "blocks_from_legacy_text",
    "document_from_legacy_text",
    "extract_doc_meta",
    "extract_csv",
    "extract_doc",
    "extract_docx",
    "extract_html",
    "extract_image",
    "extract_pdf",
    "extract_pdf_document",
    "extract_pptx",
    "extract_pptx_document",
    "extract_rtf",
    "extract_spreadsheet",
    "extract_spreadsheet_document",
    "extract_text",
    "extract_xls",
    "extract_xls_document",
    "extract_xlsx",
    "extract_xlsx_document",
    "ocr_pdf",
]
